services:
  db:
    image: postgres:16-alpine
    ports:
      - "5432:5432"
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: fanstage
    volumes:
      - fanstage_pg:/var/lib/postgresql/data

volumes:
  fanstage_pg:
